server:
  port: 8090
piloting:
  rxtx:
    serial-port-name: /dev/ttyS0
    baud-rate: 9600
  line:
    startStation:
      longitude: 111.8712902
      latitude: 21.8754195
      name: 新秀
    endStation:
      longitude: 111.877607
      latitude: 21.858466
      name: 前海湾
    cameraList:
      - longitude: 111.876445
        latitude: 21.8690705
        deviceSerial: K30567517
        name: 道口
        url: rtsp://admin:abc12345@192.168.0.206:554/h265/ch1/main/av_stream
        id: 0
        ip: 192.168.0.206
        port: 8000
        user: admin
        psw: abc12345
        sSerialNumber: DS-IPC-B12H-I20200108AACHE09823228 #设备序列号
  judgment:
    model: 2 #拉取摄像头计算方式 1：方向，2距离
    position:
      position-expireTime: 8000 #数据过期期间间隔 ms 默认8秒
      position-store-interval: 1000 #数据计算间隔 ms
      position-queueCapacity: 20 #位置队列容量
    direction:
      enable: false #是否计算方向
      direction-judgment-position-count: 6 #判断方向的位置的数量
      direction-judgment-interval-meter: 1.5 #开始移动时判断距离
      direction-score-threshold: 3 #开始方向计算得分，大于等于此值才判断分数有效
      direction-calculate-interval: 5000 #多久间隔计算一次方向 默认5s
    start:
      lineStart-judgment-position-Count: 10 #判断开始的位置的数量
      start-judgment-interval-meter: 1.5  #开始移动时判断距离
      start-direction-score-threshold: 5 #开始方向计算得分，大于等于此值才判断分数有效
    end:
      line-end-judgment-position-count: 10 #终点判断位置数量
      line-end-satisfy-distance-count: 7 #到站有效位置数量
      line-end-satisfy-distance-meter: 100 #到站时站点距离
    camera:
      pull-camera-judgment-position-count: 6 #判断拉取摄像头位置的数量
      pull-camera-satisfy-distance-meter: 800 #拉取摄像头的符合距离的大小
      pull-camera-satisfy-distance-count: 3 #拉取摄像头的符合距离的位置个数，必须低于采集的数量
      pull-camera-judgment-interval-meter: 1.5 #拉取摄像头方向时判断距离
      pull-camera-over-position-count: 6 #摄像头离开位置的数量
      pull-camera-direction-score-threshold: 2 #拉取摄像头方向计算得分，大于等于此值才判断分数有效
      camera-over-satisfy-distance-meter: 800 #驶离多远算摄像头离站
      camera-over-satisfy-distance-count: 3 #摄像头离站效位置数量
      now-camera-refresh-push-interval: 5000 #摄像头拉流刷新时间
      now-camera-refresh-over-interval: 5000 #摄像头拉流刷新时间
    stop:
      line-stop-judgment-position-count: 15 #判断停车的位置的数量
      line-stop-judgment-variance: 2 #停车位置数据的方差大小 小于等于此值算停车
      line-stop-judgment-time-interval: 5000 #停车位置计算时间间隔
  alarm:
    model: 2 #1萤石云 2 listen
    first-delay-time: 8000 #第一次延迟8s播报
    search-time-forward-millis: 5000 #查询时向时间（即告警过期时间）默认5s
    search-time-millis-interval: 3000 #查询间隔时间 默认3s
    alarm-interval: 5000 #间隔时间 默认2s 2秒内只告警一次（用于主动监听）
    noalarm-interval: 5000 #无告警间隔时间
    alarm-type: #告警类型，默认为-1（全部）
      - 10002
    dwAlarmType: #移动侦测、视频丢失、遮挡、IO信号量等报警信息(V3.0以上版本支持的设备)
      - 3
    status: 0 #告警消息状态：2-所有，1-已读，0-未读，默认为0（未读状态）
    camera-listen: 1 #1主动监听 2主动查询
  run:
    netty: false
    serial: false
    log: true
    generate: false
log:
  path: ../log
  level: DEBUG